names=raised_exception
visibility=public
kind=defined
source_location=refm/api/src/_builtin/TracePoint:491

--- raised_exception -> Exception

発生した例外を返します。

@raise RuntimeError :raise イベントのためのイベントフックの外側で実行し
                    た場合に発生します。

//emlist[例][ruby]{
trace = TracePoint.new(:raise) do |tp|
  tp.raised_exception # => #<ZeroDivisionError: divided by 0>
end
trace.enable
begin
  0/0
rescue
end
//}

